language: android

env:
  matrix:
    - ANDROID_TARGET=android-25 ANDROID_ABI=armeabi-v7a

services: mongodb

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - tools
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25

    # Additional components
    - extra

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-18
    # - sys-img-x86-android-19
  jdk: oraclejdk8

#before_script:
# Create and start emulator
#    - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#    - emulator -avd test -no-skin -no-audio -no-window &
#    - adb wait-for-device
#    - adb shell input keyevent 82 &

script:
    - ./gradlew :app:clean :app:build :app:test
    - ./gradlew :server:npmInstall :server:test
    - ./gradlew :server:integration
